### ISSUE TITLE
Problem bei der App "Datz"

### ISSUE THREAD

**Issue by MikaGieres** [Krecharles/Datz#10]
Gudden Owend, ech wollt Iech nemmen informéieren dass bei der 3e Sektioun F feelt Biologie als Kuer.

Ech wär dankbar wann Dir et keint änneren. Merci am Virraus, Mika

**Comment by Krecharles** [comment]
Moien,
Merci fir den Feedback. 
Ech hunn Bio lo dobai gemach mam update 2.1.2. Den update ass an e puer deeg accessible. 
Et muss awer eng nei klass op Datz créeiert ginn fir dass d'Bio dobai kennt.

**Comment by MikaGieres** [comment]
Ok villmols Merci😊

Von meinem iPhone gesendet
