### ISSUE TITLE
Section I

### ISSUE THREAD

**Issue by f11-f** [Krecharles/Datz#16]
The classes of 3e, 2e and 1ère do not have the informatics section (i).

**Comment by Krecharles** [comment]
Added I-section

**Comment by f11-f** [comment]
Thank you. Also for classique? Because I don’t see them.

**Comment by Krecharles** [comment]
I pushed the update today but it still needs to be accepted by apple. Expect changes to occur in about a week

**Comment by f11-f** [comment]
Ok thank you :)

**Comment by Krecharles** [comment]
You're welcome :)
