### ISSUE TITLE
Divide by 0 Error

### ISSUE THREAD

**Issue by MauriceSchreiner** [Krecharles/Datz#17]
If you put in as Denominator 0, Datz will crash immediatly and not be able to restart again. I had to reinstall Datz. A friend of mine restarted his iPad and that helped too.

**Comment by Krecharles** [comment]
I've fixed it, it is now impossible to input 0 as a maxGrade. I have a few other tweaks in mind for the next weeks, so I won't push this update immediately. Expect changes to occur on our device only in a few weeks time
