### ISSUE TITLE
SciNa

### ISSUE THREAD

**Issue by clawan** [Krecharles/Datz#18]
Gudde Metteg
Fir 6c rëchent App travaux pratiques wei wann et eng Prüfung wier. Prüfungen zielen zu 3/4. Pratikumen zb (5x15):4. daat dann dee 1/4 dee bei dei 3/4 derbei kommen.
Ech hoffen ech hu mech verständlech ausgedrëckt
LG

**Comment by Krecharles** [comment]
Fairen Punkt, passt leider net ganz an d'Architektur vun der App. En fix wier et d'notte vun der prüfung 3x anzeginn an dei vum TP (adaptéiert op 60) eng kéier anzeginn,
