### ISSUE TITLE
Eng Datz fir „Datz!“

### ISSUE THREAD

**Issue by LucGaasch** [Krecharles/Datz#19]
Gudde Mëtteg,
Leider froe mech ëmmer erëm Schüler, ob ech mech net verrechent hunn a verweisen dann op déi ominéis App ‚Datz!‘.
An do muss ech leider feststellen, datt Moyennen dilettantesch gerechent ginn. Wéi een um Screenshot gesäit, kënnt ee Schüler anscheinend op eng Moyenne vun 50 wann en eemol 30/60 an zweemol 30/30 hat. 
Dobäi ass jo fir ee Schüler aus de Grondschoul kloer, datt 2*30=60 ass. An och 30+60=90 kann een do rechnen, an mat 90/2=45 hunn se do och kee Problem. 
Anescht gesäit et bei der App ‚Datz!‘ aus, do kënnt dann 50 eraus. 

Mäi professionnelle Verdikt: Datz!

Wat eng Ironie... Dofir hoffen ech, datt dee Bug schnellstméiglech behuewe gëtt.

Mat beschte Gréiss, 
Luc Gaasch

PS: Natierlech weess ech, datt (30+60+60)/5=50 ass, mee esou fonktionnéiert d‘Moyenne-Rechnen net, a wann ee Schüler dat esou wéilt gerechent hunn, da misst Dir him dat vläit als Optioun ubidden. Mee de facto ass d‘Moyenne-Rechnen mat Prüfungen, déi net all op 60 ginn, Schrott.

![A79CA9A8-34A3-4473-9753-33E693896BE2](https://user-images.githubusercontent.com/12149741/107148829-ac5f5e80-6955-11eb-9b3b-59fdcb2b3c19.png)

**Comment by Krecharles** [comment]
Daat ass indeed en problem. Merci fir den detaileierten bug report, ech probeieren mech d'nächst woch drems ze kemmeren

**Comment by Krecharles** [comment]
Hunn et gefixed, den update misst d'nächst woch oder sou rauskommen
