### ISSUE TITLE
Deleting Notes

### ISSUE THREAD

**Issue by kyleisheree** [Krecharles/Datz#23]
Hello , I love hte programm and i have been using for a year now. I just noticed that i can not delete a unwanted note or a false note i put in. Side of that everything is perfect.

**Comment by ketchopman** [comment]
> Hello , I love hte programm and i have been using for a year now. I just noticed that i can not delete a unwanted note or a false note i put in. Side of that everything is perfect.


You can delete them by swiping left on them.

**Comment by Krecharles** [comment]
Added this to the Q&A. I tried adding a trashcan icon to the rows but it just wouldn't look alright so I guess the Q&A info should suffice
