### ISSUE TITLE
3ème Sektion I

### ISSUE THREAD

**Issue by Mr-LegitHD** [Krecharles/Datz#28]
In the 3ème Sektion I the subject "Maiou is missing

**Comment by Krecharles** [comment]
They changed a lot last year, I'm gonna implement this table. Please let me know if there is something wrong with it.
I'll also update the 2e and 1e Section I. 
![image](https://user-images.githubusercontent.com/14015470/189089487-22f451ff-84dd-43ad-8fab-2b6dff7fa1de.png)
