### ISSUE TITLE
2GMM+ 1GMM is missing. 

### ISSUE THREAD

**Issue by kyleisheree** [Krecharles/Datz#40]
Hello, I think the section Media,Marketing and Communication is missing. This is a commercial section in the ECG School.

**Comment by Krecharles** [comment]
Thanks for the notice. Could you please provide a list of subjects + coefficients so that i can add them?

**Comment by kyleisheree** [comment]
Hello, thank you for the fast reply!
I have attached a photo with this email.

**Comment by Krecharles** [comment]
The image didn't come through, could you send directly to chkremer17@gmail.com?

**Comment by Krecharles** [comment]
Will be fixed in the next update
