### ISSUE TITLE
Issue when note is half

### ISSUE THREAD

**Issue by TomR00** [Krecharles/Datz#5]
Error melding probably because the note is a double and the camma must be replaced with a point
![8EFD05FE-D664-465D-8065-58DB036A272B](https://user-images.githubusercontent.com/42215986/70435348-ed748e00-1a86-11ea-928e-7110358c946b.jpeg)

**Comment by Krecharles** [comment]
That is indeed no longer working.
The source of the bug can be:
1. a new iOS update does no longer accept a comma
2. It depends whether the iPhone language is set to english or german/french

I will look into it as soon as I find the time, 1ere is currently very stressful.

Thank you for your feedback!

**Comment by Krecharles** [comment]
Fixed this issue on commit 090fe4b37f1b3acde879d9a12635273a1895839e.
The fix will be included in the next update
