### ISSUE TITLE
D'Gesamtmoyenne gëtt falsch verrechent

### ISSUE THREAD

**Issue by CreativeYann2004** [Krecharles/Datz#54]
D'Gesamtmoyenne gëtt mat de Kommazuele gerechent an net mat den opgerënnten Note vun den eenzelne Fächer. D'Gesamtmoyenne gëtt och nët méi opgeronnt. 
Merci fir déi praktesch App!

**Comment by Krecharles** [comment]
Merci fir den Feedback, ech hunn den Fehler fonnt an behuewen. An e puer Deeg misst den update rauskommen.
Dass d'Gesamt moyenne net opgeronnt gett ass absichtlech, dann kritt een e besseren iwwerbleck weivill punkten een nach brauch fir sech ze verbesseren.

Merci fir d'Kompliment, et freet mech dass der d'App nëtzlech ass!
