### ISSUE TITLE
cannot edit grade that is in a combi 4GIG

### ISSUE THREAD

**Issue by KawaiiDragon69** [Krecharles/Datz#56]
The combi Citoyenneté cannot be edited in any way the grades that were already there before the problem stay however when I try to add a new grade both of the subjects are blank, I've tried creating a new combi and it doesn't work. I've also seen this happening to more people

**Comment by Krecharles** [comment]
Fixed the Problem. Thanks for reporting this error! The new version will be available in a few days.
