### ISSUE TITLE
German Translation of all Classes/Already a german translation accessible?

### ISSUE THREAD

**Issue by MauriceSchreiner** [Krecharles/Datz#8]
Hello, I am currently on a PC so I can't simply disect the source code of Datz! to see if there is a german translation. I would write one if there's none.

**Comment by Maurice855** [comment]
[All ClassesDE.xlsx](https://github.com/Krecharles/Datz/files/4525098/All.ClassesDE.xlsx)

**Comment by Krecharles** [comment]
Hi! Thanks for getting in touch! I am going to set up some localisation so that you can write the german translations in one file. I'll get to you once I'm done.

**Comment by Krecharles** [comment]
Added german localisation in commit a6da9fd030d33ee6229d0b71098645e3972d2823.

The way localisation is set up is that the app is using the same language as the iPhone system language and if that language has not been translated yet, it falls back to english.
You can now edit the strings in the file Datz!/View/de.lproj/Main.strings. In line 3 I translated one string to show you how it's done. Feel free to contact me if you're not sure if you doing it correctly!

Thanks for helping, I really appreciate it! :)

**Comment by Krecharles** [comment]
I realized that I forgot many dynamic localisations, especially class names. Added them in commit 7a5f470e102b5d74637455d86cae939439366945. These can now be altered  in the file Datz!/View/de.lproj/Localizable.strings. I know there are many classnames, potentially even duplicates. Not everything needs to be translated, do just as you feel is sensible.

**Comment by MauriceSchreiner** [comment]
[de.lproj.zip](https://github.com/Krecharles/Datz/files/4531724/de.lproj.zip)

I've led especially the french shortcuts as original because Vie et Societé should never be translated, that would be Leben und Gesellschaft; LeuGe

**Comment by Krecharles** [comment]
Thanks! Your translations are very accurate, no need to worry. I would have done the same. I integrated your translations in the commit b8080815ca2e6098bca2fcfede2eb5ba54934475.
The update 2.1.1 will be available in a few days in the app store. Thanks again for your help!
